In [1]:
from llm.tokenizer import Tokenizer, benchmark_tokenizer
from llm.common import serialize_token_ids

In [2]:
dataset = "owt_train.txt"

tokenizer = Tokenizer.from_files("vocab_owt_train.json", "owt_train_merges.txt")

In [3]:
tokenizer.encode("bah")

[98, 993]

In [4]:
tokenizer.decode(_)

'bah'

In [5]:
result = benchmark_tokenizer(tokenizer, dataset)

Benchmarking encode: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████| 52.4M/52.4M [01:03<00:00, 824kB/s, MiB_s=0.78, run=5]


In [6]:
result

{'sample_mib': 10.001286506652832,
 'bytes_per_second': 826376.2635070313,
 'mib_per_second': 0.7880938181944191,
 'runs_mib_per_second': [0.7880938181944191,
  0.7861281807449935,
  0.7944223454647714,
  0.7919387164198313,
  0.7844726006900414],
 'tokens_processed': 11958210}

In [13]:
mib_per_sec = result['mib_per_second']
gib_in_mib = 1e9 / 1000 ** 2

In [ ]:
hours = (((gib_in_mib / mib_per_sec) / 60) * 12) / 60
print(f"hours to encode owt: {hours}")

In [6]:
import numpy as np

In [8]:
all_ids = []
with open("data/owt_train.txt") as f:
    for _id in tokenizer.encode_iterable(f):
        all_ids.append(_id)
arr = np.array(all_ids, dtype=np.uint16)

serialize_token_ids("owt.npy", arr)

In [9]:
len(all_ids)

2741514793

In [7]:
tokens = np.load("owt.npy")

In [8]:
len(tokens)

2741514793

In [9]:
tokens[0:100]

array([ 2001,  3384,   696,   361,   473,   284,  3890,  2046,   361,
        1880,    63,    10,    10,  2070,  1079,  7644,  7600,   279,
         321,   258,  3253, 11807,  1447,    44,   258,  3735,  1066,
         919,   350,  2637,   288,  6680,  9796,    44, 19420,    44,
         294, 21594, 11485,   539,    46,    10,    10, 26981,   321,
         258, 15312,   423,  8144,  2104,    46,  1442,   330,   115,
        2935,   634,  1183,  3321,   294, 16944,   284,  1818,   949,
        1893,   284,  8095,   687,  1171,   679,   321,    46, 10452,
         453,  2396,  2334,   679,   330,   115,  1599,  5819,    58,
         634,  6554,    44,   634,  1532,    44,   294,   634,  2452,
         329,  1169,   506,    46,    10,    10,    74,   277,   321,
         258], dtype=uint16)

In [10]:
tokenizer.decode(tokens[0:100])

"What wouldn't you do to save someone you love?\n\nWhen They Come Calling is a modern ghost story, a suspenseful weaving of urban battles, romance, and supernatural intrigue.\n\nAnna is a physician from Kansas City. She’s spent her life giving and caring to others while trying to hide how different she is. Anna has lost everyone she’s ever loved: her relationships, her family, and her hope for something more.\n\nJed is a"

In [14]:
tokenizer.decode(tokens[len(tokens)-100:])

'autical miles off the shore. The agreement also stipulated that Israel would expand the area gradually up to 12 miles.\n\nPalestinian fishermen, however, say the Israeli navy opens fire on them before they reach the agreed limit. About 4,000 fishermen work in Gaza, half of whom live below the poverty line.\n\nThe Gaza Strip has been under an Israeli blockade since June 2007. The blockade has caused unprecedented levels of unemployment and unrelenting poverty.<|endoftext|>'

In [33]:
from einops import einsum, rearrange
import torch

In [44]:
x = torch.tensor([1,2])
print(x.shape)
W = torch.tensor([[1,2],[3,4], [4,5]])
print(W.shape)
print(W.T.shape)
y = x @ W.T
print(y.shape)
y

torch.Size([2])
torch.Size([3, 2])
torch.Size([2, 3])
torch.Size([3])


tensor([ 5, 11, 14])

In [47]:
einsum(x, W, "input, output input -> output")

tensor([ 5, 11, 14])

In [1]:
from llm.nn import Linear

In [2]:
linear = Linear(2,3)

In [9]:
linear.state_dict()

OrderedDict([('W',
              tensor([[ 0.1262,  0.8121, -0.7128],
                      [ 0.4267,  0.1402,  0.2151]]))])